import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '../styles/Home.module.css';
import Popular from '../components/Popular';
import Veggie from '../components/Veggie';
import { useEffect } from 'react';
import { motion } from 'framer-motion';
import Layout from '../components/Layout';

export const getStaticProps = async () => {
    const [popularRes, veggieRes] = await Promise.all([
        fetch(
            `https://api.spoonacular.com/recipes/random?apiKey=${process.env.NEXT_PUBLIC_APP_API_KEY}&number=9`
        ),
        fetch(
            `https://api.spoonacular.com/recipes/random?apiKey=${process.env.NEXT_PUBLIC_APP_API_KEY}&number=9&tags=vegetarian`
        ),
    ]);

    const [popularData, veggieData] = await Promise.all([
        popularRes.json(),
        veggieRes.json(),
    ]);

    // console.log('hehe');
    // console.log(data);
    return {
        props: { popular: popularData.recipes, veggie: veggieData.recipes },
    };
};

export default function Home({ popular, veggie }: any) {
    return (
        <>
            <Head>
                <title>Delicious - Home</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <motion.div className="" key={'/'}>
                    <Veggie veggie={veggie} />

                    <Popular popular={popular} />
                </motion.div>
            </Layout>
        </>
    );
}
